name: build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - java: 1.8
          - java: 11.0          
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.config.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.config.java }}
      - name: Build with Maven
        run: mvn -B clean package
