name: release
on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  release_assets:
    name: Release assets
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0
      - name: Build with Maven
        run: mvn -B clean package
      - name: Set jar name
        run: echo "JAR_NAME=target/${GITHUB_REPOSITORY#joeygibson/}-1.0-SNAPSHOT.jar" >> $GITHUB_ENV
      - name: Set distribution jar name
        run: echo "DIST_JAR_NAME=${GITHUB_REPOSITORY#joeygibson/}-${GITHUB_REF#refs/*/v}.jar" >> $GITHUB_ENV
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: ${{ env.DIST_JAR_NAME }}
          asset_path: ${{ env.JAR_NAME }}
          asset_content_type: application/octet-stream
  